# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_brooks_simple.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(829, 448)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.controller = QtWidgets.QTabWidget(self.centralwidget)
        self.controller.setMinimumSize(QtCore.QSize(240, 0))
        self.controller.setToolTip("")
        self.controller.setToolTipDuration(-1)
        self.controller.setElideMode(QtCore.Qt.ElideNone)
        self.controller.setMovable(False)
        self.controller.setObjectName("controller")
        self.controlTab = QtWidgets.QWidget()
        self.controlTab.setToolTip("")
        self.controlTab.setToolTipDuration(-1)
        self.controlTab.setObjectName("controlTab")
        self.gridLayout = QtWidgets.QGridLayout(self.controlTab)
        self.gridLayout.setObjectName("gridLayout")
        self.pv_1 = QtWidgets.QLineEdit(self.controlTab)
        self.pv_1.setEnabled(False)
        self.pv_1.setMaximumSize(QtCore.QSize(70, 16777215))
        self.pv_1.setObjectName("pv_1")
        self.gridLayout.addWidget(self.pv_1, 0, 0, 1, 1)
        self.sp_1 = QtWidgets.QDoubleSpinBox(self.controlTab)
        self.sp_1.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.sp_1.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.sp_1.setObjectName("sp_1")
        self.gridLayout.addWidget(self.sp_1, 0, 1, 1, 1)
        self.frame = QtWidgets.QFrame(self.controlTab)
        self.frame.setMinimumSize(QtCore.QSize(500, 200))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.graphicsWindow = GraphicsLayoutWidget()
        self.graphicsWindow.setObjectName("graphicsWindow")
        self.gridLayout_2.addWidget(self.graphicsWindow, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pb_start = QtWidgets.QPushButton(self.frame)
        self.pb_start.setCheckable(True)
        self.pb_start.setAutoExclusive(True)
        self.pb_start.setObjectName("pb_start")
        self.horizontalLayout.addWidget(self.pb_start)
        self.pb_stop = QtWidgets.QPushButton(self.frame)
        self.pb_stop.setEnabled(False)
        self.pb_stop.setCheckable(True)
        self.pb_stop.setAutoExclusive(True)
        self.pb_stop.setObjectName("pb_stop")
        self.horizontalLayout.addWidget(self.pb_stop)
        self.gridLayout_2.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 2, 10, 1)
        self.pv_2 = QtWidgets.QLineEdit(self.controlTab)
        self.pv_2.setEnabled(False)
        self.pv_2.setMaximumSize(QtCore.QSize(70, 16777215))
        self.pv_2.setObjectName("pv_2")
        self.gridLayout.addWidget(self.pv_2, 1, 0, 1, 1)
        self.sp_2 = QtWidgets.QDoubleSpinBox(self.controlTab)
        self.sp_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.sp_2.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.sp_2.setObjectName("sp_2")
        self.gridLayout.addWidget(self.sp_2, 1, 1, 1, 1)
        self.pv_3 = QtWidgets.QLineEdit(self.controlTab)
        self.pv_3.setEnabled(False)
        self.pv_3.setMaximumSize(QtCore.QSize(70, 16777215))
        self.pv_3.setObjectName("pv_3")
        self.gridLayout.addWidget(self.pv_3, 2, 0, 1, 1)
        self.sp_3 = QtWidgets.QDoubleSpinBox(self.controlTab)
        self.sp_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.sp_3.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.sp_3.setObjectName("sp_3")
        self.gridLayout.addWidget(self.sp_3, 2, 1, 1, 1)
        self.pv_4 = QtWidgets.QLineEdit(self.controlTab)
        self.pv_4.setEnabled(False)
        self.pv_4.setMaximumSize(QtCore.QSize(70, 16777215))
        self.pv_4.setObjectName("pv_4")
        self.gridLayout.addWidget(self.pv_4, 3, 0, 1, 1)
        self.sp_4 = QtWidgets.QDoubleSpinBox(self.controlTab)
        self.sp_4.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.sp_4.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.sp_4.setObjectName("sp_4")
        self.gridLayout.addWidget(self.sp_4, 3, 1, 1, 1)
        self.pv_5 = QtWidgets.QLineEdit(self.controlTab)
        self.pv_5.setEnabled(False)
        self.pv_5.setMaximumSize(QtCore.QSize(70, 16777215))
        self.pv_5.setObjectName("pv_5")
        self.gridLayout.addWidget(self.pv_5, 4, 0, 1, 1)
        self.sp_5 = QtWidgets.QDoubleSpinBox(self.controlTab)
        self.sp_5.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.sp_5.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.sp_5.setObjectName("sp_5")
        self.gridLayout.addWidget(self.sp_5, 4, 1, 1, 1)
        self.pv_6 = QtWidgets.QLineEdit(self.controlTab)
        self.pv_6.setEnabled(False)
        self.pv_6.setMaximumSize(QtCore.QSize(70, 16777215))
        self.pv_6.setObjectName("pv_6")
        self.gridLayout.addWidget(self.pv_6, 5, 0, 1, 1)
        self.sp_6 = QtWidgets.QDoubleSpinBox(self.controlTab)
        self.sp_6.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.sp_6.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.sp_6.setObjectName("sp_6")
        self.gridLayout.addWidget(self.sp_6, 5, 1, 1, 1)
        self.pv_7 = QtWidgets.QLineEdit(self.controlTab)
        self.pv_7.setEnabled(False)
        self.pv_7.setMaximumSize(QtCore.QSize(70, 16777215))
        self.pv_7.setObjectName("pv_7")
        self.gridLayout.addWidget(self.pv_7, 6, 0, 1, 1)
        self.sp_7 = QtWidgets.QDoubleSpinBox(self.controlTab)
        self.sp_7.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.sp_7.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.sp_7.setObjectName("sp_7")
        self.gridLayout.addWidget(self.sp_7, 6, 1, 1, 1)
        self.pv_8 = QtWidgets.QLineEdit(self.controlTab)
        self.pv_8.setEnabled(False)
        self.pv_8.setMaximumSize(QtCore.QSize(70, 16777215))
        self.pv_8.setObjectName("pv_8")
        self.gridLayout.addWidget(self.pv_8, 7, 0, 1, 1)
        self.sp_8 = QtWidgets.QDoubleSpinBox(self.controlTab)
        self.sp_8.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.sp_8.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.sp_8.setObjectName("sp_8")
        self.gridLayout.addWidget(self.sp_8, 7, 1, 1, 1)
        self.pv_9 = QtWidgets.QLineEdit(self.controlTab)
        self.pv_9.setEnabled(False)
        self.pv_9.setMaximumSize(QtCore.QSize(70, 16777215))
        self.pv_9.setObjectName("pv_9")
        self.gridLayout.addWidget(self.pv_9, 8, 0, 1, 1)
        self.sp_9 = QtWidgets.QDoubleSpinBox(self.controlTab)
        self.sp_9.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.sp_9.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.sp_9.setObjectName("sp_9")
        self.gridLayout.addWidget(self.sp_9, 8, 1, 1, 1)
        self.pv_10 = QtWidgets.QLineEdit(self.controlTab)
        self.pv_10.setEnabled(False)
        self.pv_10.setMaximumSize(QtCore.QSize(70, 16777215))
        self.pv_10.setObjectName("pv_10")
        self.gridLayout.addWidget(self.pv_10, 9, 0, 1, 1)
        self.sp_10 = QtWidgets.QDoubleSpinBox(self.controlTab)
        self.sp_10.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.sp_10.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.sp_10.setObjectName("sp_10")
        self.gridLayout.addWidget(self.sp_10, 9, 1, 1, 1)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/default/icones/led-grey-icon-16x16.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.controller.addTab(self.controlTab, icon, "")
        self.fsTab = QtWidgets.QWidget()
        self.fsTab.setToolTip("")
        self.fsTab.setToolTipDuration(-1)
        self.fsTab.setObjectName("fsTab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.fsTab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tag_1 = QtWidgets.QLineEdit(self.fsTab)
        self.tag_1.setEnabled(True)
        self.tag_1.setMaximumSize(QtCore.QSize(70, 16777215))
        self.tag_1.setObjectName("tag_1")
        self.gridLayout_3.addWidget(self.tag_1, 0, 0, 1, 1)
        self.port_1 = QtWidgets.QComboBox(self.fsTab)
        self.port_1.setObjectName("port_1")
        self.port_1.addItem("")
        self.gridLayout_3.addWidget(self.port_1, 0, 1, 1, 1)
        self.gaz_1 = QtWidgets.QLineEdit(self.fsTab)
        self.gaz_1.setEnabled(True)
        self.gaz_1.setMaximumSize(QtCore.QSize(70, 16777215))
        self.gaz_1.setObjectName("gaz_1")
        self.gridLayout_3.addWidget(self.gaz_1, 0, 2, 1, 1)
        self.fs_1 = QtWidgets.QLineEdit(self.fsTab)
        self.fs_1.setEnabled(False)
        self.fs_1.setObjectName("fs_1")
        self.gridLayout_3.addWidget(self.fs_1, 0, 3, 1, 1)
        self.unit_1 = QtWidgets.QLineEdit(self.fsTab)
        self.unit_1.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.unit_1.setReadOnly(True)
        self.unit_1.setObjectName("unit_1")
        self.gridLayout_3.addWidget(self.unit_1, 0, 4, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(257, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 0, 5, 1, 1)
        self.tag_2 = QtWidgets.QLineEdit(self.fsTab)
        self.tag_2.setEnabled(True)
        self.tag_2.setMaximumSize(QtCore.QSize(70, 16777215))
        self.tag_2.setObjectName("tag_2")
        self.gridLayout_3.addWidget(self.tag_2, 1, 0, 1, 1)
        self.port_2 = QtWidgets.QComboBox(self.fsTab)
        self.port_2.setObjectName("port_2")
        self.port_2.addItem("")
        self.gridLayout_3.addWidget(self.port_2, 1, 1, 1, 1)
        self.gaz_2 = QtWidgets.QLineEdit(self.fsTab)
        self.gaz_2.setEnabled(True)
        self.gaz_2.setMaximumSize(QtCore.QSize(70, 16777215))
        self.gaz_2.setObjectName("gaz_2")
        self.gridLayout_3.addWidget(self.gaz_2, 1, 2, 1, 1)
        self.fs_2 = QtWidgets.QLineEdit(self.fsTab)
        self.fs_2.setEnabled(False)
        self.fs_2.setObjectName("fs_2")
        self.gridLayout_3.addWidget(self.fs_2, 1, 3, 1, 1)
        self.unit_2 = QtWidgets.QLineEdit(self.fsTab)
        self.unit_2.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.unit_2.setReadOnly(True)
        self.unit_2.setObjectName("unit_2")
        self.gridLayout_3.addWidget(self.unit_2, 1, 4, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(257, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 1, 5, 1, 1)
        self.tag_3 = QtWidgets.QLineEdit(self.fsTab)
        self.tag_3.setEnabled(True)
        self.tag_3.setMaximumSize(QtCore.QSize(70, 16777215))
        self.tag_3.setObjectName("tag_3")
        self.gridLayout_3.addWidget(self.tag_3, 2, 0, 1, 1)
        self.port_3 = QtWidgets.QComboBox(self.fsTab)
        self.port_3.setObjectName("port_3")
        self.port_3.addItem("")
        self.gridLayout_3.addWidget(self.port_3, 2, 1, 1, 1)
        self.gaz_3 = QtWidgets.QLineEdit(self.fsTab)
        self.gaz_3.setEnabled(True)
        self.gaz_3.setMaximumSize(QtCore.QSize(70, 16777215))
        self.gaz_3.setObjectName("gaz_3")
        self.gridLayout_3.addWidget(self.gaz_3, 2, 2, 1, 1)
        self.fs_3 = QtWidgets.QLineEdit(self.fsTab)
        self.fs_3.setEnabled(False)
        self.fs_3.setObjectName("fs_3")
        self.gridLayout_3.addWidget(self.fs_3, 2, 3, 1, 1)
        self.unit_3 = QtWidgets.QLineEdit(self.fsTab)
        self.unit_3.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.unit_3.setReadOnly(True)
        self.unit_3.setObjectName("unit_3")
        self.gridLayout_3.addWidget(self.unit_3, 2, 4, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(257, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 2, 5, 1, 1)
        self.tag_4 = QtWidgets.QLineEdit(self.fsTab)
        self.tag_4.setEnabled(True)
        self.tag_4.setMaximumSize(QtCore.QSize(70, 16777215))
        self.tag_4.setObjectName("tag_4")
        self.gridLayout_3.addWidget(self.tag_4, 3, 0, 1, 1)
        self.port_4 = QtWidgets.QComboBox(self.fsTab)
        self.port_4.setObjectName("port_4")
        self.port_4.addItem("")
        self.gridLayout_3.addWidget(self.port_4, 3, 1, 1, 1)
        self.gaz_4 = QtWidgets.QLineEdit(self.fsTab)
        self.gaz_4.setEnabled(True)
        self.gaz_4.setMaximumSize(QtCore.QSize(70, 16777215))
        self.gaz_4.setObjectName("gaz_4")
        self.gridLayout_3.addWidget(self.gaz_4, 3, 2, 1, 1)
        self.fs_4 = QtWidgets.QLineEdit(self.fsTab)
        self.fs_4.setEnabled(False)
        self.fs_4.setObjectName("fs_4")
        self.gridLayout_3.addWidget(self.fs_4, 3, 3, 1, 1)
        self.unit_4 = QtWidgets.QLineEdit(self.fsTab)
        self.unit_4.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.unit_4.setReadOnly(True)
        self.unit_4.setObjectName("unit_4")
        self.gridLayout_3.addWidget(self.unit_4, 3, 4, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(257, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem3, 3, 5, 1, 1)
        self.tag_5 = QtWidgets.QLineEdit(self.fsTab)
        self.tag_5.setEnabled(True)
        self.tag_5.setMaximumSize(QtCore.QSize(70, 16777215))
        self.tag_5.setObjectName("tag_5")
        self.gridLayout_3.addWidget(self.tag_5, 4, 0, 1, 1)
        self.port_5 = QtWidgets.QComboBox(self.fsTab)
        self.port_5.setObjectName("port_5")
        self.port_5.addItem("")
        self.gridLayout_3.addWidget(self.port_5, 4, 1, 1, 1)
        self.gaz_5 = QtWidgets.QLineEdit(self.fsTab)
        self.gaz_5.setEnabled(True)
        self.gaz_5.setMaximumSize(QtCore.QSize(70, 16777215))
        self.gaz_5.setObjectName("gaz_5")
        self.gridLayout_3.addWidget(self.gaz_5, 4, 2, 1, 1)
        self.fs_5 = QtWidgets.QLineEdit(self.fsTab)
        self.fs_5.setEnabled(False)
        self.fs_5.setObjectName("fs_5")
        self.gridLayout_3.addWidget(self.fs_5, 4, 3, 1, 1)
        self.unit_5 = QtWidgets.QLineEdit(self.fsTab)
        self.unit_5.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.unit_5.setReadOnly(True)
        self.unit_5.setObjectName("unit_5")
        self.gridLayout_3.addWidget(self.unit_5, 4, 4, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(257, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem4, 4, 5, 1, 1)
        self.tag_6 = QtWidgets.QLineEdit(self.fsTab)
        self.tag_6.setEnabled(True)
        self.tag_6.setMaximumSize(QtCore.QSize(70, 16777215))
        self.tag_6.setObjectName("tag_6")
        self.gridLayout_3.addWidget(self.tag_6, 5, 0, 1, 1)
        self.port_6 = QtWidgets.QComboBox(self.fsTab)
        self.port_6.setObjectName("port_6")
        self.port_6.addItem("")
        self.gridLayout_3.addWidget(self.port_6, 5, 1, 1, 1)
        self.gaz_6 = QtWidgets.QLineEdit(self.fsTab)
        self.gaz_6.setEnabled(True)
        self.gaz_6.setMaximumSize(QtCore.QSize(70, 16777215))
        self.gaz_6.setObjectName("gaz_6")
        self.gridLayout_3.addWidget(self.gaz_6, 5, 2, 1, 1)
        self.fs_6 = QtWidgets.QLineEdit(self.fsTab)
        self.fs_6.setEnabled(False)
        self.fs_6.setObjectName("fs_6")
        self.gridLayout_3.addWidget(self.fs_6, 5, 3, 1, 1)
        self.unit_6 = QtWidgets.QLineEdit(self.fsTab)
        self.unit_6.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.unit_6.setReadOnly(True)
        self.unit_6.setObjectName("unit_6")
        self.gridLayout_3.addWidget(self.unit_6, 5, 4, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(257, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem5, 5, 5, 1, 1)
        self.tag_7 = QtWidgets.QLineEdit(self.fsTab)
        self.tag_7.setEnabled(True)
        self.tag_7.setMaximumSize(QtCore.QSize(70, 16777215))
        self.tag_7.setObjectName("tag_7")
        self.gridLayout_3.addWidget(self.tag_7, 6, 0, 1, 1)
        self.port_7 = QtWidgets.QComboBox(self.fsTab)
        self.port_7.setObjectName("port_7")
        self.port_7.addItem("")
        self.gridLayout_3.addWidget(self.port_7, 6, 1, 1, 1)
        self.gaz_7 = QtWidgets.QLineEdit(self.fsTab)
        self.gaz_7.setEnabled(True)
        self.gaz_7.setMaximumSize(QtCore.QSize(70, 16777215))
        self.gaz_7.setObjectName("gaz_7")
        self.gridLayout_3.addWidget(self.gaz_7, 6, 2, 1, 1)
        self.fs_7 = QtWidgets.QLineEdit(self.fsTab)
        self.fs_7.setEnabled(False)
        self.fs_7.setObjectName("fs_7")
        self.gridLayout_3.addWidget(self.fs_7, 6, 3, 1, 1)
        self.unit_7 = QtWidgets.QLineEdit(self.fsTab)
        self.unit_7.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.unit_7.setReadOnly(True)
        self.unit_7.setObjectName("unit_7")
        self.gridLayout_3.addWidget(self.unit_7, 6, 4, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(257, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem6, 6, 5, 1, 1)
        self.tag_8 = QtWidgets.QLineEdit(self.fsTab)
        self.tag_8.setEnabled(True)
        self.tag_8.setMaximumSize(QtCore.QSize(70, 16777215))
        self.tag_8.setObjectName("tag_8")
        self.gridLayout_3.addWidget(self.tag_8, 7, 0, 1, 1)
        self.port_8 = QtWidgets.QComboBox(self.fsTab)
        self.port_8.setObjectName("port_8")
        self.port_8.addItem("")
        self.gridLayout_3.addWidget(self.port_8, 7, 1, 1, 1)
        self.gaz_8 = QtWidgets.QLineEdit(self.fsTab)
        self.gaz_8.setEnabled(True)
        self.gaz_8.setMaximumSize(QtCore.QSize(70, 16777215))
        self.gaz_8.setObjectName("gaz_8")
        self.gridLayout_3.addWidget(self.gaz_8, 7, 2, 1, 1)
        self.fs_8 = QtWidgets.QLineEdit(self.fsTab)
        self.fs_8.setEnabled(False)
        self.fs_8.setObjectName("fs_8")
        self.gridLayout_3.addWidget(self.fs_8, 7, 3, 1, 1)
        self.unit_8 = QtWidgets.QLineEdit(self.fsTab)
        self.unit_8.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.unit_8.setReadOnly(True)
        self.unit_8.setObjectName("unit_8")
        self.gridLayout_3.addWidget(self.unit_8, 7, 4, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(257, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem7, 7, 5, 1, 1)
        self.tag_9 = QtWidgets.QLineEdit(self.fsTab)
        self.tag_9.setEnabled(True)
        self.tag_9.setMaximumSize(QtCore.QSize(70, 16777215))
        self.tag_9.setObjectName("tag_9")
        self.gridLayout_3.addWidget(self.tag_9, 8, 0, 1, 1)
        self.port_9 = QtWidgets.QComboBox(self.fsTab)
        self.port_9.setObjectName("port_9")
        self.port_9.addItem("")
        self.gridLayout_3.addWidget(self.port_9, 8, 1, 1, 1)
        self.gaz_9 = QtWidgets.QLineEdit(self.fsTab)
        self.gaz_9.setEnabled(True)
        self.gaz_9.setMaximumSize(QtCore.QSize(70, 16777215))
        self.gaz_9.setObjectName("gaz_9")
        self.gridLayout_3.addWidget(self.gaz_9, 8, 2, 1, 1)
        self.fs_9 = QtWidgets.QLineEdit(self.fsTab)
        self.fs_9.setEnabled(False)
        self.fs_9.setObjectName("fs_9")
        self.gridLayout_3.addWidget(self.fs_9, 8, 3, 1, 1)
        self.unit_9 = QtWidgets.QLineEdit(self.fsTab)
        self.unit_9.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.unit_9.setReadOnly(True)
        self.unit_9.setObjectName("unit_9")
        self.gridLayout_3.addWidget(self.unit_9, 8, 4, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(257, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem8, 8, 5, 1, 1)
        self.tag_10 = QtWidgets.QLineEdit(self.fsTab)
        self.tag_10.setEnabled(True)
        self.tag_10.setMaximumSize(QtCore.QSize(70, 16777215))
        self.tag_10.setObjectName("tag_10")
        self.gridLayout_3.addWidget(self.tag_10, 9, 0, 1, 1)
        self.port_10 = QtWidgets.QComboBox(self.fsTab)
        self.port_10.setObjectName("port_10")
        self.port_10.addItem("")
        self.gridLayout_3.addWidget(self.port_10, 9, 1, 1, 1)
        self.gaz_10 = QtWidgets.QLineEdit(self.fsTab)
        self.gaz_10.setEnabled(True)
        self.gaz_10.setMaximumSize(QtCore.QSize(70, 16777215))
        self.gaz_10.setObjectName("gaz_10")
        self.gridLayout_3.addWidget(self.gaz_10, 9, 2, 1, 1)
        self.fs_10 = QtWidgets.QLineEdit(self.fsTab)
        self.fs_10.setEnabled(False)
        self.fs_10.setObjectName("fs_10")
        self.gridLayout_3.addWidget(self.fs_10, 9, 3, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(257, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem9, 9, 5, 1, 1)
        self.unit_10 = QtWidgets.QLineEdit(self.fsTab)
        self.unit_10.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.unit_10.setReadOnly(True)
        self.unit_10.setObjectName("unit_10")
        self.gridLayout_3.addWidget(self.unit_10, 9, 4, 1, 1)
        self.controller.addTab(self.fsTab, "")
        self.gridLayout_4.addWidget(self.controller, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 829, 26))
        self.menubar.setObjectName("menubar")
        self.menuFichier = QtWidgets.QMenu(self.menubar)
        self.menuFichier.setObjectName("menuFichier")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionQuitter = QtWidgets.QAction(MainWindow)
        self.actionQuitter.setObjectName("actionQuitter")
        self.actionConnect = QtWidgets.QAction(MainWindow)
        self.actionConnect.setObjectName("actionConnect")
        self.menuFichier.addAction(self.actionQuitter)
        self.menuFichier.addAction(self.actionConnect)
        self.menubar.addAction(self.menuFichier.menuAction())
        self.toolBar.addAction(self.actionQuitter)
        self.toolBar.addAction(self.actionConnect)

        self.retranslateUi(MainWindow)
        self.controller.setCurrentIndex(0)
        self.actionQuitter.triggered.connect(MainWindow.close)
        self.pb_start.clicked['bool'].connect(self.pb_start.setDisabled)
        self.pb_start.clicked['bool'].connect(self.pb_stop.setEnabled)
        self.pb_stop.clicked['bool'].connect(self.pb_stop.setDisabled)
        self.pb_stop.clicked['bool'].connect(self.pb_start.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.controller, self.pv_1)
        MainWindow.setTabOrder(self.pv_1, self.sp_1)
        MainWindow.setTabOrder(self.sp_1, self.pv_2)
        MainWindow.setTabOrder(self.pv_2, self.sp_2)
        MainWindow.setTabOrder(self.sp_2, self.pv_3)
        MainWindow.setTabOrder(self.pv_3, self.sp_3)
        MainWindow.setTabOrder(self.sp_3, self.pv_4)
        MainWindow.setTabOrder(self.pv_4, self.sp_4)
        MainWindow.setTabOrder(self.sp_4, self.pv_5)
        MainWindow.setTabOrder(self.pv_5, self.sp_5)
        MainWindow.setTabOrder(self.sp_5, self.pv_6)
        MainWindow.setTabOrder(self.pv_6, self.sp_6)
        MainWindow.setTabOrder(self.sp_6, self.pv_7)
        MainWindow.setTabOrder(self.pv_7, self.sp_7)
        MainWindow.setTabOrder(self.sp_7, self.pv_8)
        MainWindow.setTabOrder(self.pv_8, self.sp_8)
        MainWindow.setTabOrder(self.sp_8, self.pv_9)
        MainWindow.setTabOrder(self.pv_9, self.sp_9)
        MainWindow.setTabOrder(self.sp_9, self.pv_10)
        MainWindow.setTabOrder(self.pv_10, self.sp_10)
        MainWindow.setTabOrder(self.sp_10, self.graphicsWindow)
        MainWindow.setTabOrder(self.graphicsWindow, self.pb_start)
        MainWindow.setTabOrder(self.pb_start, self.pb_stop)
        MainWindow.setTabOrder(self.pb_stop, self.tag_1)
        MainWindow.setTabOrder(self.tag_1, self.port_1)
        MainWindow.setTabOrder(self.port_1, self.gaz_1)
        MainWindow.setTabOrder(self.gaz_1, self.fs_1)
        MainWindow.setTabOrder(self.fs_1, self.unit_1)
        MainWindow.setTabOrder(self.unit_1, self.tag_2)
        MainWindow.setTabOrder(self.tag_2, self.port_2)
        MainWindow.setTabOrder(self.port_2, self.gaz_2)
        MainWindow.setTabOrder(self.gaz_2, self.fs_2)
        MainWindow.setTabOrder(self.fs_2, self.unit_2)
        MainWindow.setTabOrder(self.unit_2, self.tag_3)
        MainWindow.setTabOrder(self.tag_3, self.port_3)
        MainWindow.setTabOrder(self.port_3, self.gaz_3)
        MainWindow.setTabOrder(self.gaz_3, self.fs_3)
        MainWindow.setTabOrder(self.fs_3, self.unit_3)
        MainWindow.setTabOrder(self.unit_3, self.tag_4)
        MainWindow.setTabOrder(self.tag_4, self.port_4)
        MainWindow.setTabOrder(self.port_4, self.gaz_4)
        MainWindow.setTabOrder(self.gaz_4, self.fs_4)
        MainWindow.setTabOrder(self.fs_4, self.unit_4)
        MainWindow.setTabOrder(self.unit_4, self.tag_5)
        MainWindow.setTabOrder(self.tag_5, self.port_5)
        MainWindow.setTabOrder(self.port_5, self.gaz_5)
        MainWindow.setTabOrder(self.gaz_5, self.fs_5)
        MainWindow.setTabOrder(self.fs_5, self.unit_5)
        MainWindow.setTabOrder(self.unit_5, self.tag_6)
        MainWindow.setTabOrder(self.tag_6, self.port_6)
        MainWindow.setTabOrder(self.port_6, self.gaz_6)
        MainWindow.setTabOrder(self.gaz_6, self.fs_6)
        MainWindow.setTabOrder(self.fs_6, self.unit_6)
        MainWindow.setTabOrder(self.unit_6, self.tag_7)
        MainWindow.setTabOrder(self.tag_7, self.port_7)
        MainWindow.setTabOrder(self.port_7, self.gaz_7)
        MainWindow.setTabOrder(self.gaz_7, self.fs_7)
        MainWindow.setTabOrder(self.fs_7, self.unit_7)
        MainWindow.setTabOrder(self.unit_7, self.tag_8)
        MainWindow.setTabOrder(self.tag_8, self.port_8)
        MainWindow.setTabOrder(self.port_8, self.gaz_8)
        MainWindow.setTabOrder(self.gaz_8, self.fs_8)
        MainWindow.setTabOrder(self.fs_8, self.unit_8)
        MainWindow.setTabOrder(self.unit_8, self.tag_9)
        MainWindow.setTabOrder(self.tag_9, self.port_9)
        MainWindow.setTabOrder(self.port_9, self.gaz_9)
        MainWindow.setTabOrder(self.gaz_9, self.fs_9)
        MainWindow.setTabOrder(self.fs_9, self.unit_9)
        MainWindow.setTabOrder(self.unit_9, self.tag_10)
        MainWindow.setTabOrder(self.tag_10, self.port_10)
        MainWindow.setTabOrder(self.port_10, self.gaz_10)
        MainWindow.setTabOrder(self.gaz_10, self.fs_10)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MFC-58XX"))
        self.sp_1.setPrefix(_translate("MainWindow", "H2 Event = "))
        self.sp_1.setSuffix(_translate("MainWindow", " unit"))
        self.pb_start.setText(_translate("MainWindow", "Start"))
        self.pb_stop.setText(_translate("MainWindow", "Stop"))
        self.sp_2.setPrefix(_translate("MainWindow", "H2 Resist = "))
        self.sp_2.setSuffix(_translate("MainWindow", " unit"))
        self.sp_3.setPrefix(_translate("MainWindow", "Ar Resist = "))
        self.sp_3.setSuffix(_translate("MainWindow", " unit"))
        self.sp_4.setPrefix(_translate("MainWindow", "H2 Liner = "))
        self.sp_4.setSuffix(_translate("MainWindow", " unit"))
        self.sp_5.setPrefix(_translate("MainWindow", "Ar Liner = "))
        self.sp_5.setSuffix(_translate("MainWindow", " unit"))
        self.sp_6.setPrefix(_translate("MainWindow", "N2 Liner = "))
        self.sp_6.setSuffix(_translate("MainWindow", " unit"))
        self.sp_7.setPrefix(_translate("MainWindow", "SiH4 Liner = "))
        self.sp_7.setSuffix(_translate("MainWindow", " unit"))
        self.sp_8.setPrefix(_translate("MainWindow", "C3H8 Liner = "))
        self.sp_8.setSuffix(_translate("MainWindow", " unit"))
        self.sp_9.setPrefix(_translate("MainWindow", "aux Liner = "))
        self.sp_9.setSuffix(_translate("MainWindow", " unit"))
        self.sp_10.setPrefix(_translate("MainWindow", "aux2 = "))
        self.sp_10.setSuffix(_translate("MainWindow", " unit"))
        self.controller.setTabText(self.controller.indexOf(self.controlTab), _translate("MainWindow", "Consignes"))
        self.tag_1.setText(_translate("MainWindow", "28478010"))
        self.port_1.setItemText(0, _translate("MainWindow", "---"))
        self.gaz_1.setText(_translate("MainWindow", "gaz 1"))
        self.fs_1.setText(_translate("MainWindow", "FS = "))
        self.unit_1.setText(_translate("MainWindow", "unit"))
        self.port_2.setItemText(0, _translate("MainWindow", "---"))
        self.gaz_2.setText(_translate("MainWindow", "gaz 2"))
        self.fs_2.setText(_translate("MainWindow", "FS = "))
        self.unit_2.setText(_translate("MainWindow", "unit"))
        self.port_3.setItemText(0, _translate("MainWindow", "---"))
        self.gaz_3.setText(_translate("MainWindow", "gaz 3"))
        self.fs_3.setText(_translate("MainWindow", "FS = "))
        self.unit_3.setText(_translate("MainWindow", "unit"))
        self.port_4.setItemText(0, _translate("MainWindow", "---"))
        self.gaz_4.setText(_translate("MainWindow", "gaz 4"))
        self.fs_4.setText(_translate("MainWindow", "FS = "))
        self.unit_4.setText(_translate("MainWindow", "unit"))
        self.port_5.setItemText(0, _translate("MainWindow", "---"))
        self.gaz_5.setText(_translate("MainWindow", "gaz 5"))
        self.fs_5.setText(_translate("MainWindow", "FS = "))
        self.unit_5.setText(_translate("MainWindow", "unit"))
        self.port_6.setItemText(0, _translate("MainWindow", "---"))
        self.gaz_6.setText(_translate("MainWindow", "gaz 6"))
        self.fs_6.setText(_translate("MainWindow", "FS = "))
        self.unit_6.setText(_translate("MainWindow", "unit"))
        self.port_7.setItemText(0, _translate("MainWindow", "---"))
        self.gaz_7.setText(_translate("MainWindow", "gaz 7"))
        self.fs_7.setText(_translate("MainWindow", "FS = "))
        self.unit_7.setText(_translate("MainWindow", "unit"))
        self.port_8.setItemText(0, _translate("MainWindow", "---"))
        self.gaz_8.setText(_translate("MainWindow", "gaz 8"))
        self.fs_8.setText(_translate("MainWindow", "FS = "))
        self.unit_8.setText(_translate("MainWindow", "unit"))
        self.port_9.setItemText(0, _translate("MainWindow", "---"))
        self.gaz_9.setText(_translate("MainWindow", "gaz 9"))
        self.fs_9.setText(_translate("MainWindow", "FS = "))
        self.unit_9.setText(_translate("MainWindow", "unit"))
        self.port_10.setItemText(0, _translate("MainWindow", "---"))
        self.gaz_10.setText(_translate("MainWindow", "gaz 10"))
        self.fs_10.setText(_translate("MainWindow", "FS = "))
        self.unit_10.setText(_translate("MainWindow", "unit"))
        self.controller.setTabText(self.controller.indexOf(self.fsTab), _translate("MainWindow", "Config"))
        self.menuFichier.setTitle(_translate("MainWindow", "Fichier"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionQuitter.setText(_translate("MainWindow", "Quitter"))
        self.actionConnect.setText(_translate("MainWindow", "Connect"))
from pyqtgraph import GraphicsLayoutWidget #old=GraphicsWindow
import ressource_rc
